Prismatic Motor (GPT-Helped)

Discritize

In [3]:
import numpy as np

# Motor parameters from user
J = 7.88e-8        # kg·m²
b = 8.391e-4       # N·m·s/rad
KT = 0.06002       # Nm/A
Ke = 0.06080       # V·s/rad
R = 0.924          # Ohm
L = 0.08778        # Henry

# Continuous-time A matrix
A = np.array([
    [0, 1, 0, 0],
    [0, -b/J, -1/J, KT/J],
    [0, 0, 0, 0],
    [0, -Ke/L, 0, -R/L]
])

# Continuous-time B matrix
B = np.array([
    [0],
    [0],
    [0],
    [1/L]
])

# Noise influence matrix G
G = np.array([
    [0],
    [0],
    [1],
    [0]
])

# Measurement matrix C (theta and current)
C = np.array([
    [1, 0, 0, 0],
    [0, 0, 0, 1]
])

A, B, G, C


(array([[ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -1.06484772e+04, -1.26903553e+07,
          7.61675127e+05],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          0.00000000e+00],
        [ 0.00000000e+00, -6.92640693e-01,  0.00000000e+00,
         -1.05263158e+01]]),
 array([[ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [11.39211666]]),
 array([[0],
        [0],
        [1],
        [0]]),
 array([[1, 0, 0, 0],
        [0, 0, 0, 1]]))

In [4]:
import numpy as np
from scipy.signal import cont2discrete

# Discretize the system using zero-order hold (ZOH)
system_discrete = cont2discrete((Ac, Bc, C, 0), Ts, method='zoh')
Ad, Bd, Cd, Dd, _ = system_discrete

Ad, Bd, Cd

ModuleNotFoundError: No module named 'scipy'